version: "3.6"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.9.4
    environment:
      - USER_UID=1002
      - USER_GID=1002
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - /data/etc/gitea:/data
    expose:
      - 3001
      - 3080
      - 22
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
    networks:
      - gitea
    volumes:
      - /data/etc/gitea/mariadb:/var/lib/mysql
